server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-user
    username: postgres
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: amqps://ipipenvx:uY7ow_eqXolY1OIJUKFJ8CK8XfxsB4j_@beaver.rmq.cloudamqp.com/ipipenvx
    broker:
      queue:
        email:
          name: default.email