server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email
    username: postgres
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: amqps://ipipenvx:uY7ow_eqXolY1OIJUKFJ8CK8XfxsB4j_@beaver.rmq.cloudamqp.com/ipipenvx
    broker:
      queue:
        email:
          name: default.email
  mail:
    host: smtp.gmail.com
    port: 587
    username: l****@gmail.com
    password: /*** **** **** ****
    properties:
      mail:
        smtp:
          auth: true
        smtp.starttls.enable: true